# Generated by Django 3.0.7 on 2020-07-15 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_auto_20200711_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=250)),
                ('isMany', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='patientapp.QuestionTitle'),
            preserve_default=False,
        ),
    ]
