# Generated by Django 3.0.7 on 2020-07-15 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0007_remove_question_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patientapp.QuestionTitle'),
            preserve_default=False,
        ),
    ]
