# Generated by Django 3.0.7 on 2020-07-17 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0008_question_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='InitialQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(default='', max_length=200)),
                ('row', models.IntegerField(default=0)),
                ('question_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patientapp.QuestionTitle')),
            ],
        ),
    ]
