# Generated by Django 3.0.7 on 2020-07-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0009_auto_20200717_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialquestion',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='patientapp.Patient'),
            preserve_default=False,
        ),
    ]
