# Generated by Django 3.0.7 on 2020-07-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0010_initialquestion_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialquestion',
            name='question_title',
        ),
    ]
