# Generated by Django 3.0.7 on 2020-07-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0014_questiontitle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodanalysis',
            name='pok',
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='cd20',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='cd3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='cd4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='cd8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='iga',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='igg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='igm',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='immunogram',
            name='tge',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
