# Generated by Django 3.1 on 2020-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0015_auto_20200722_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodanalysis',
            name='act',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bloodanalysis',
            name='alt',
            field=models.FloatField(default=0),
        ),
    ]
