# Generated by Django 3.1 on 2020-08-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0016_auto_20200811_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Immunogram',
        ),
    ]
