# Generated by Django 3.0.7 on 2020-07-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20200705_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='ethambutol',
            new_name='constipation',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='pyrazinamide',
            new_name='normal_stool',
        ),
    ]
