# Generated by Django 3.0.7 on 2020-07-15 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_auto_20200715_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
    ]
