# Generated by Django 3.0.7 on 2020-07-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0011_remove_initialquestion_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initialquestion',
            name='row',
        ),
    ]
