# Generated by Django 3.0.7 on 2020-07-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0013_auto_20200717_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiontitle',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
