# Generated by Django 3.1 on 2020-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name1', models.CharField(max_length=25)),
                ('feature_name2', models.CharField(max_length=25)),
                ('sub_value1', models.FloatField()),
                ('sub_value2', models.FloatField()),
                ('l_R', models.FloatField(default=0)),
                ('r_R', models.FloatField(default=0)),
            ],
        ),
    ]
