# Generated by Django 3.0.7 on 2020-06-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='region',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Region')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.District'),
        ),
    ]
