# Generated by Django 3.0.7 on 2020-06-25 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200624_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dateofapp',
        ),
        migrations.AddField(
            model_name='patient',
            name='fromdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
