# Generated by Django 3.0.7 on 2020-06-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200625_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
