# Generated by Django 3.0.7 on 2020-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200625_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.District'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Occupation'),
            preserve_default=False,
        ),
    ]
