# Generated by Django 3.0.7 on 2020-07-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200625_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
